services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1884:1883"
    command: mosquitto -c /mosquitto-no-auth.conf

  world:
    build:
      context: ../../
      dockerfile: deployments/docker/world/Dockerfile
    ports:
      - "8081:8081"

  coordinator:
    build:
      context: ../../
      dockerfile: deployments/docker/coordinator/Dockerfile
    ports:
      - "8080:8080"
      - "9001:9001/udp"
      - "9002:9002"
    environment:
      - WORLD_ADDR=http://world:8081
      - MQTT_BROKER=tcp://mosquitto:1884
    depends_on:
      - mosquitto

  detector:
    build:
      context: ../../
      dockerfile: deployments/docker/detector/Dockerfile
    depends_on:
      - coordinator
      - world
      - mosquitto
    environment:
      - COORDINATOR_ADDR=http://coordinator:8080
      - WORLD_ADDR=http://world:8081
      - UDP_ADDR=coordinator:9001
      - MQTT_BROKER=tcp://mosquitto:1884
    deploy:
      replicas: 3

  cleaner:
    build:
      context: ../../
      dockerfile: deployments/docker/servicebot/Dockerfile
    depends_on:
      - coordinator
      - mosquitto
    environment:
      - BOT_TYPE=cleaner
      - COORD_ADDR=http://coordinator:8080
      - COORD_UDP=coordinator:9001
      - COORD_GRPC=coordinator:9002
      - GRPC_PORT=50051
      - MQTT_BROKER=tcp://mosquitto:1884
    deploy:
      replicas: 2

  repair:
    build:
      context: ../../
      dockerfile: deployments/docker/servicebot/Dockerfile
    depends_on:
      - coordinator
      - mosquitto
    environment:
      - BOT_TYPE=repair
      - COORD_ADDR=http://coordinator:8080
      - COORD_UDP=coordinator:9001
      - COORD_GRPC=coordinator:9002
      - GRPC_PORT=50051
      - MQTT_BROKER=tcp://mosquitto:1884
    deploy:
      replicas: 2
