services:
  world:
    build:
      context: ../../
      dockerfile: deployments/docker/world/Dockerfile
    ports:
      - "8081:8081"

  coordinator:
    build:
      context: ../../
      dockerfile: deployments/docker/coordinator/Dockerfile
    ports:
      - "8080:8080"
      - "9001:9001/udp"

  detector:
    build:
      context: ../../
      dockerfile: deployments/docker/detector/Dockerfile
    depends_on:
      - coordinator
      - world
    environment:
      - COORDINATOR_ADDR=http://coordinator:8080
      - WORLD_ADDR=http://world:8081
      - UDP_ADDR=coordinator:9001
    deploy:
      replicas: 3

  cleaner:
    build:
      context: ../../
      dockerfile: deployments/docker/servicebot/Dockerfile
    depends_on:
      - coordinator
    environment:
      - BOT_TYPE=cleaner
    deploy:
      replicas: 2

  repair:
    build:
      context: ../../
      dockerfile: deployments/docker/servicebot/Dockerfile
    depends_on:
      - coordinator
    environment:
      - BOT_TYPE=repair
    deploy:
      replicas: 2
